# .travis.yml
dist: xenial
sudo: required
language: node_js
node_js:
 - "lts/*"
              
   #before_install:
   # - sudo apt-get install -y git-ftp
   #addons:
   #  apt:
   #    update: true

install:
 - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
 - sudo dpkg -i /tmp/hugo.deb

before_script:
 - npm install -g 
 - bower install
 - npm install -g gulp-cli  

script:
 - gulp build
 - hugo
 - cd $TRAVIS_BUILD_DIR
 - chmod +x deploy.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
